name = "demo-bbird-cdn"
main = "index.js"
compatibility_date = "2026-03-13"
workers_dev = true
account_id = "ac7ee4615628005dc5ba0a22f0aae2a6"

routes = [
   { pattern = "demo.bbird.live/*", zone_name = "bbird.live" },
]

[vars]
ORIGIN_HOSTNAME = "main--demo--scdemos.aem.live"
PUSH_INVALIDATION = "enabled"

[observability.logs]
enabled = true
