name: Deploy CDN Worker

on:
  push:
    branches: [main]
    paths:
      - 'workers/cdn/**/*.js'
      - 'workers/cdn/wrangler.toml'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-worker.yaml
    secrets: inherit
    with:
      working-directory: workers/cdn
