name: Deploy Auth Worker

on:
  push:
    branches: [main]
    paths:
      - 'workers/auth/**/*.js'
      - 'workers/auth/wrangler.toml'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-worker.yaml
    secrets: inherit
    with:
      working-directory: workers/auth
